version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: elixir_kafka_consumer
    ports:
      - 5432:5432
